name: Publish new Docker image

on:
  release:
    types: [published]

jobs:
  dockerhub-build-push:
    name: DockerHub Build and Push
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Get the current release version 
      id: vars
      run: echo ::set-output name=tag::$(echo ${GITHUB_REF:10})
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag tfgco/kubectl:latest --tag tfgco/kubectl:${{steps.vars.outputs.tag}} --tag tfgco/kubectl:aws-cli --tag tfgco/kubectl:${{steps.vars.outputs.tag}}-aws-cli
    - name: Login to DockerHub Registry
      run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
    - name: Push the latest Docker image
      run: docker push --all-tags tfgco/kubectl
  quayio-build-push:
    name: Quay.io Build and Push
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Get the current release version 
      id: vars
      run: echo ::set-output name=tag::$(echo ${GITHUB_REF:10})
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag quay.io/tfgco/kubectl:latest --tag quay.io/tfgco/kubectl:${{steps.vars.outputs.tag}} --tag quay.io/tfgco/kubectl:aws-cli --tag quay.io/tfgco/kubectl:${{steps.vars.outputs.tag}}-aws-cli
    - name: Login to Quay.io Registry
      run: echo ${{ secrets.QUAYIO_TOKEN }} | docker login -u ${{ secrets.QUAYIO_USERNAME }} --password-stdin quay.io
    - name: Push the latest Docker image
      run: docker push --all-tags quay.io/tfgco/kubectl
